<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="minimal-ui,width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <title>旧机回收</title>
        <meta name="keywords" content="线下,线下系统,线下以旧换新,线下系统以旧换新"/>
        <meta name="description" content="先下,线下系统,线下以旧换新,线下系统以旧换新"/>
        <link rel="stylesheet" href="<?php echo IMG01_DOMAIN; ?>/common/swiper4.5.0/swiper.min.css">
        <link type="text/css" rel="stylesheet" href="/css/common/new0917/common.min.css?v=<?php echo v_css;?>"/>
        <link type="text/css" rel="stylesheet" href="/css/promoter/product/index.css?v=190927<?php echo v_css;?>"/>
        <script type="text/javascript" src="<?php echo IMG01_DOMAIN; ?>/common/jquery-1.11.2.min.js"></script>
        <script src="<?php echo IMG01_DOMAIN; ?>/common/swiper4.5.0/swiper.min.js" type="text/javascript" charset="utf-8"></script>
    </head>
    <body id="ydmBody">

        <div class="gome_offline_contain">
            <div class="swiper_banner_container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                            <img src="/images/offlinem/index/banner.jpg?v=0926">
                    </div>
                </div>
            </div>

            <div class="main_list_category">
                <div class="type_list_header clearfix">
                    <div class="left pfm icon_type">回收品类</div>
                    <div class="right">品类更全 数量更多</div>
                </div>
                <ul>
                    <li>
                        <a href="/offlinem/brand/list?mertype=J">
                            <img src="https://img01.youdemai.com/images/ydmapp/index/285/classify_J.png" />
                            <div class="text">手机</div>
                        </a>
                    </li>
                    <li>
                        <a href="/offlinem/brand/list?mertype=L">
                            <img src="https://img01.youdemai.com/images/ydmapp/index/285/classify_L.png" />
                            <div class="text">笔记本</div>
                        </a>
                    </li>
                    <li>
                        <a href="/offlinem/brand/list?mertype=K">
                            <img src="https://img01.youdemai.com/images/ydmapp/index/285/classify_K.png" />
                            <div class="text">平板</div>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/offlinem/brand/list?mertype=A">
                            <img src="https://img01.youdemai.com/images/ydmapp/index/285/classify_A.png" />
                            <div class="text">摄影摄像</div>
                        </a>
                    </li>
                    <li>
                        <a href="/offlinem/brand/list?mertype=CD">
                            <img src="https://img01.youdemai.com/images/ydmapp/index/285/classify_CD.png" />
                            <div class="text">智能数码</div>
                        </a>
                    </li>
                    <li>
                        <a href="/offlinem/brand/list?mertype=J">
                            <img src="https://img01.youdemai.com/images/ydmapp/index/285/classify_more.png" />
                            <div class="text">更多品类</div>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="hot_mer_box">
              <div class="type_list_header clearfix">
                <div class="left pfb hot">热门回收</div>
                <div class="right">PC、数码行业NO.1</div>
              </div>
              <div class="hot_mer_list clearfix">
                <div class="mer_list thembg" tabindex="J" ydm-recycle-hottypes="ydmM02_D_J">手机</div>
                <div class="mer_list" tabindex="K" ydm-recycle-hottypes="ydmM02_D_K">平板</div>
                <div class="mer_list" tabindex="A" ydm-recycle-hottypes="ydmM02_D_A">相机</div>
                <div class="mer_list" tabindex="CPU" ydm-recycle-hottypes="ydmM02_D_CPU">电脑配件</div>
                <div class="mer_list" tabindex="CD" ydm-recycle-hottypes="ydmM02_D_CD">智能设备</div>
              </div>
              <div class="hot_box">
                <div class="hot actived">
                  <ul class="clearfix"></ul>
                </div>
              </div>
            </div>


            <!-- 32项检测 -->
<!--            <div class="step_box">-->
<!--                <div class="type_list_header more_item clearfix">-->
<!--                    <div class="left pfb check">专业检测</div>-->
<!--                    <a href="/offlinem/info/check"><div class="right nav_right">开创行业检测标准</div></a>-->
<!--                </div>-->
<!--                <div class="check_out">-->
<!--                    <div class="check_box">-->
<!--                        <div><img src="https://img01.youdemai.com/images/ydmweb/index/check1.png" alt=""></div>-->
<!--                        <div><img src="https://img01.youdemai.com/images/ydmweb/index/check2.png" alt=""></div>-->
<!--                        <div><img src="https://img01.youdemai.com/images/ydmweb/index/check3.png" alt=""></div>-->
<!--                        <div><img src="https://img01.youdemai.com/images/ydmweb/index/check4.png" alt=""></div>-->
<!--                        <div><img src="https://img01.youdemai.com/images/ydmweb/index/check5.png" alt=""></div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
            <!--合作伙伴-->
<!--            <div class="menu_partner">-->
<!--                <div class="type_list_header clearfix">-->
<!--                    <div class="left pfm partner">合作伙伴</div>-->
<!--                    <div class="right">多家官方服务商</div>-->
<!--                </div>-->
<!--                <div class="swiper-partner">-->
<!--                    <div class="swiper-wrapper">-->
<!--                        <div class="swiper-slide img"><img src="https://img01.youdemai.com/images/ydmapp/index/285/partner_logo3.png"/></div>-->
<!--                        <div class="swiper-slide img"><img src="https://img01.youdemai.com/images/ydmapp/index/285/partner_logo1.png"/></div>-->
<!--                        <div class="swiper-slide img"><img src="https://img01.youdemai.com/images/ydmapp/index/285/partner_logo2.png"/></div>-->
<!--                    </div>-->
<!--                    <div class="swiper-pagination"></div>-->
<!--              </div>-->
<!---->
<!--            </div>-->
        </div>
        <div class="footer" id="footer">
            <div class="api_bottom index active" apihref="/offlinem/product/index">首页</div>
            <div class="api_bottom classify" apihref="/offlinem/brands/index">分类</div>
            <div class="api_bottom center" apihref="/offlinem/brands/indexw">我的</div>
<!--            <div class="api_bottom center" apihref="/offlinem/center">我的</div>-->
        </div>
    </body>
<script type="text/javascript" src="/js/view/offlinem/common/common.min.js?v=<?php echo v_js;?>"></script>
<script type="text/javascript">
    //banner图轮播
//  var mySwiper = new Swiper('.swiper_banner_container',{
//      pagination:'.swiper-pagination',
//      paginationClickable:true,
//      loop:true,
//      autoplay:3000
//  });
//
    //合作伙伴轮播
    var partnerSwiper = new Swiper('.swiper-partner', {
        pagination:'.swiper-pagination',
        spaceBetween:30,
        autoplay:5000,
        loop:true
    });

getHotmer('J');
$('.hot_mer_list .mer_list').bind('click',function(){
    var dataSpm = $(this).attr('ydm-recycle-hottypes');
    $('.hot_mer_list .mer_list').removeClass('thembg');
    var index = $(this).addClass('thembg').attr('tabindex');
    getHotmer(index);
});


var typeArr =[];
function getHotmer(index){
    $.ajax({type:'GET',dataType:'jsonp',jsonp:'jsonp_callback',cache:false,async:false,
        data:{merType:index,num:'4'},
        url:'https://openapi.youdemai.com/products/hot/hotproduct',
        success:function(data){
            var html = '';var imgUrl = '';
            for(var i in data.hotMer){
                var hrefUrl = '/offlinem/inquiry/init?spid='+data.hotMer[i].SPID;
                imgUrl = 'https://images.youdemai.com/nwimages/images/thumbs/'+data.hotMer[i].MERIMG;
                html += '<li class="img">';
                    html += '<a href="'+hrefUrl+'">';
                        html += '<img class="mer_img" src="'+imgUrl+'" />';
                        html += '<div class="mer_name ellipsis">'+data.hotMer[i].MERNAME+'</div>';
                    html += '</a>';
                html += '</li>';
            }
            $('.hot_box .hot .clearfix').html(html);
        }
    });
};


</script>

</html>