<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta content="width=device-width, height=device-height, minimum-scale=1, maximum-scale=1" name="viewport" />
    <meta name="format-detection" content="telephone=no, email=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>个人中心</title>
    <meta name="keywords" content="线下,线下系统,线下以旧换新,线下系统以旧换新"/>
    <meta name="description" content="线下,线下系统,线下以旧换新,线下系统以旧换新"/>
    <link type="text/css" rel="stylesheet" href="/css/common/new0917/common.min.css?v=<?php echo v_css;?>"/>
    <script type="text/javascript" src="<?php echo IMG01_DOMAIN; ?>/common/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/js/layer/mobile/layer.mobile.js?v=<?php echo v_js;?>"></script>
    <script type="text/javascript" src="<?php echo YDMCDN01;?>/common/layer/v3.0/layer.js"></script>
    <script type="text/javascript" src="/js/validator/uiwidget-validator.min.js"></script>
    <script type="text/javascript" src="/js/validator/validator-custom-methods.js"></script>
    <script type="text/javascript" src="/js/validator/uiwidget-validator_zh_CN.js"></script>
</head>
<style>

    body{background:#f5f5f5;}
    .ct-area{background:#F5F5F5;}
    .ct-area .ct-box{padding:0.3rem;border-bottom:1px solid #ddd;border-top:1px solid #ddd;background:#fff url()no-repeat right center;background-size: 0.6rem;height:1.8rem;}
    .ct-area .ct-box .picture{float:left;width:1.2rem;height:1.8rem;}
    .ct-area .ct-box .picture img{width:100%;border-radius:1rem;}
    .ct-area .ct-box .info{float:left;padding:0.1rem 0 .1rem .3rem;;width:4rem;height:1.2rem;}
    .ct-area .ct-box .info .store_name{font-size:0.28rem;font-weight:bold;height:.6rem;line-height:.5rem;padding-bottom:.1rem;overflow:hidden;text-overflow:ellipsis;table-layout: fixed;}
    .ct-area .ct-box .info .text{font-size:.24rem;height:.4rem;line-height:.4rem;width: 3.7rem;overflow: hidden;white-space: nowrap;text-overflow: ellipsis;}


    .list_box{background:#fff;border-top:1px solid #ddd;margin-top:0.2rem}
    .list_box .all{padding:.3rem .2rem .3rem .7rem;;border-bottom:1px solid #f5f5f5;font-size:.28rem;}
    .list_box .go{background:url(/images/offlinem/invitee/center/center_go.png)no-repeat 0.1rem center;background-size:0.5rem;}
    .list_box .system{background:url(/images/offlinem/invitee/center/center_system.png)no-repeat 0.1rem center;background-size:0.4rem;}
    .list_box .help{background:url(/images/offlinem/invitee/center/center_help.png)no-repeat 0.1rem center;background-size:0.4rem;}
    .list_box .all{padding:.3rem .2rem .3rem .7rem;;border-bottom:1px solid #f5f5f5;font-size:.28rem;}
    .list_box .contacts{background:url(/images/partner/center/icon_tel.png)no-repeat 0.1rem center;background-size:0.4rem;}
    .list_box  .main{background-image:none;}
    .list_box .contacts span{float:right;}
    #lookmessage{background:#FF1744;color:#fff;}
    .loginout{display:block;width:80%;margin:0.8rem auto;line-height:0.8rem;text-align:center;background:#FF1744;color:#fff;font-size:0.25rem;border-radius:0.05rem;}
</style>
<body>

    <div id="ydmBody" class="container">
        <div class="header">
            <h1>个人中心</h1>//97 78
        </div>

            <div class="ct-area">
                <div class="ct-box clearfix">
                    <div class="picture">
                                <img style="width: 65px;height:60px" src="<?php echo $this->image;?>">

                    </div>
                    <div class="info">
                        <div class="store_name">  <input id="names" value="<?php    $name=$this->namess;  echo $name; ?>"></input></div>
                        <div class="text"><?php  $contactWay=$this->contactWay;  echo $contactWay;?></div>
                    </div>

                    <div id="lookmessage"       style="float: right;margin:40px 20px 40px auto">查看个人信息</div>

                </div>

            </div>

            </div>

        <div class="list_box">
            <a href='/offlinem/product/seeorder'><div class="all system" style=' text-align:center1'>订单详情</div></a>
            <a href='/offlinem/brands/tabindexs'><div class="all go" style=' text-align:center1'>购买商品</div></a>
            <a href='/offlinem/fenxiang/lists'><div class="all system" style=' text-align:center1'>地址管理</div></a>
<!--            <div class="all contacts clearfix">电话客服<span ><a class="main" href="tel:17855203121">17855203121</a></span></div>-->

        </div>
    <div class="loginout">退出登录</div>
    </div>


</body>
<script type="text/javascript" src="/js/view/offlinem/common/common.min.js?v=<?php echo v_js;?>"></script>
<script type="text/javascript">
    $().ready(function(){
        //登录退出
        $('.loginout').click(function(){
            layer.open({
                content: '<ul class="alter"><li class="alttop">提示</li><li class="altbody">是否确定退出？</li><ul>',
                btn: ['确定','取消'],
                shadeClose:false,
                time : 3,
                yes: function(index){
                    top.location.href = '/offlinem/login/index';
                },no:function(){
                    layer.closeAll();
                }
            });
        });
    });
</script>
<script type="text/javascript">

   $('#lookmessage').click(function () {
var names=$('#names').val();
window.location.href='/offlinem/brands/person?names='+ names;


   })



</script>
</html>