<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta content="width=device-width, height=device-height, minimum-scale=1, maximum-scale=1" name="viewport" />
    <meta name="format-detection" content="telephone=no, email=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <title>个人信息</title>
    <meta name="keywords" content="线下,线下系统,线下以旧换新,线下系统以旧换新"/>
    <meta name="description" content="线下,线下系统,线下以旧换新,线下系统以旧换新"/>
    <link type="text/css" rel="stylesheet" href="/css/common/common.min.css?v=<?php echo v_css;?>"/>
    <link type="text/css" rel="stylesheet" href="/css/offlinem/product/searchindex.min.css?v=<?php echo v_css;?>"/>
    <script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
</head>
<style>
    body{background:#f5f5f5;}
    .top{padding: 0.6rem 0.2rem;border-bottom:1px solid #ddd;background:url(/images/partner/center/informus_banner.png)no-repeat top left;background-size: 7.0rem;}
    .top .picture{float: left;width: 1rem;}
    .top .picture img{width: 1.0rem;border-radius: 0.5rem;}
    .top .info{float: left;padding-left: 0.2rem;width: 5rem;background-size: 0.3rem;}
    .top .info .store_name{color: #fff;font-size: 0.22rem;font-weight: bold;padding: 0.15rem 0;}
    .top .info .text{color: #ddd;}
    .info_head{padding: 0.2rem;background: #fff;border-bottom: 1px solid #ddd;margin-top: 0.2rem;}
    .info_head div{font-size: 0.26rem;padding-left: 0.1rem;border-left: 0.05rem solid #FF1744;font-weight: bold;}
    .list_box{background: #fff;padding: 0.1rem 0.2rem 0 0.4rem;}
    .list_box .all{padding:.3rem 0;;border-bottom:1px solid #f5f5f5;font-size:.22rem;color: #363636;}
    .list_box .all span{font-weight: bold;padding-left: 0.4rem;}
</style>
<body>
<?php
$list=$this->list;
foreach ($list as $k=>$v){


}
?>
<div id="ydmBody" class="container">
    <div class="header">
        <div id="headerGoBack" class="left"><div class="back"></div></div>
        <h1>个人信息</h1>
        <a href="/offlinem" ><div id="goHomePage" class="right"><div class="goHome"></div></div></a>
    </div>
    <div class="top clearfix">
        <div class="picture">
            <img src="<?php  echo $this->image;?>">
        </div>
        <div class="info">
            <div class="store_name"><?php echo '姓名:'.$v['NAME']?></div>
            <div class="text"><?php echo '手机号:'.$v['TELNUMBER'];?></div>
        </div>
    </div>
    <div class="info_head">
        <div>所在地址</div>
    </div>
    <div class="list_box">
        <div class="all">具体地址 <span><?php echo $v['PROVINCE'].$v['CLASS'];?></span></div>
    </div>
    <form enctype="multipart/form-data" method="POST"  >

        修改图片：<input name="uploadedfile" type="file" />
        <br />
        <input type="submit" value="确认" />
    </form>
</div>
</body>
<script type="text/javascript" src="/js/view/partner/common/common.min.js?v=<?php echo v_js;?>"></script>
</html>