<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="minimal-ui,width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <title>旧机回收</title>
    <meta name="keywords" content="线下,线下系统,线下以旧换新,线下系统以旧换新"/>
    <meta name="description" content="先下,线下系统,线下以旧换新,线下系统以旧换新"/>
    <link rel="stylesheet" href="<?php echo IMG01_DOMAIN; ?>/common/swiper4.5.0/swiper.min.css">
    <link type="text/css" rel="stylesheet" href="/css/common/new0917/common.min.css?v=<?php echo v_css;?>"/>
    <link type="text/css" rel="stylesheet" href="/css/promoter/product/index.css?v=190927<?php echo v_css;?>"/>
    <script type="text/javascript" src="<?php echo IMG01_DOMAIN; ?>/common/jquery-1.11.2.min.js"></script>
    <script src="<?php echo IMG01_DOMAIN; ?>/common/swiper4.5.0/swiper.min.js" type="text/javascript" charset="utf-8"></script>
</head>
<body id="ydmBody">
<div class="them_color"></div>
<div class="gome_offline_contain">
    <form id="addUserForm" name="addUserForm" action="/offlinem/fenxiang/list" method="post">
   <table border="1">
       <tr><td>展示排序</td><td><input  id="ids" class="ids"  /></td></tr>
       <tr><td>输入姓名</td><td><input  id="nameq" class="nameq"  /></td></tr>
       <tr><td>输入电话</td><td><input  id="telnumber" class="telnumber"  /></td></tr>
       <tr><td>输入地址：</td><td>
       <select id="province" class="province">请选择省份
<option id="province" value="">请选择省份</option>
           <?php
           if($this->province){
               foreach($this->province as $value){
                   echo '<option value="'.$value['AREA_NAME'].'">'.$value['AREA_NAME'].'</option>';
               }
           }
           ?>
</select>
               <select id="city" class="city">
                   <option value="">请选择城市</option>
               </select></td>
       </tr>
       <tr> <td>输入具体地址:</td><td><input  id="dizhi" class="dizhi"  /> </td></tr>
   </table><td></td><td colspan="2" style="text-align:center;">
        <div id="btn_submit" name="btn_submit" class="button btn_rosy">保存</div>
    </td>
    </form>
</div>

<div class="footer" id="footer">
    <div class="api_bottom index active" apihref="/offlinem/product/index">首页</div>
    <div class="api_bottom classify" apihref="/offlinem/brand/list">分类</div>
    <div class="api_bottom actity" apihref="/offlinem/fenxiang/index">分享</div>
    <div class="api_bottom center" apihref="/offlinem/center">我的</div>
</div>
</body>
<script type="text/javascript" src="/js/view/offlinem/common/common.min.js?v=<?php echo v_js;?>"></script>
<script type="text/javascript">

    $().ready(function(){

        //表单提交按钮点击事件
        $('#btn_submit').click(function(){
            $('#btn_submit').attr('disabled','disabled');


            var params = {};
            params.nameq = $('#nameq').val();
            params.ids = $('#ids').val();
            params.telnumber = $('#telnumber').val();
            params.province = $('#province').val();
             params.city = $('#city').val();
            params.dizhi = $('#dizhi').val();
            $.post('/offlinem/Fenxiang/list', params, function(result){
                if(result == 'Y'){
                    window.location.href = '/offlinem/fenxiang/lists';
                }else{
                    alert('保存失败');
                    $('#btn_submit').attr('disabled','');
                }
            });
        });
    });

</script>
</html>