<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <link type="text/css" rel="stylesheet" href="/css/common/common.min.css?v=<?php echo v_css;?>"/>

    <style type="text/css">
        .ydm_logo_container{text-align: center;padding: 0.5rem 0rem;}
        .ydm_logo_container img{width: 20%;}
        .ydm_logo_container .text{font-size: 0.22rem;font-weight: bold;padding: 0.3rem 0;font-family: "PingFang SC", "Helvetica Neue", Helvetica;}
        .mainbox{padding:.5rem 0;}
        .mainbox .btnbox{width: 80%;margin: 0 auto;line-height:1.0rem;font-size:.35rem;text-align:center;margin-bottom: 0.5rem;border-radius:.07rem;color:#fff;background: #ff1744;}
        .mainbox .regist{text-align:right;padding-right:.5rem;font-size:.24rem;font-weight: bold;}
        .mainbox .regist a{color:#EF3030;}
    </style>
  </head>
<body>

  <div class="mainbox">
    <a href="/offlinem/login/index">
      <div class="btnbox">用户入口</div>
    </a>
      <a href="/offlinem/product/xiangqing">
      <div class="btnbox">商家入口</div>
    </a>
  </div>
</body>
</html>